baseURL = "https://devin0x01.github.io"
languageCode = "en-us"
title = "DEVIN's BLOG"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "DEVIN"
  description = "In solitude, where we are least alone."
  github = "devin0x01"
#  facebook = "devin"
  twitter = "home"
#  linkedin = "devin"
#  instagram = "devin"
#  tumblr = "devin"
#  email = "anon#gmail.com"
  url = "https://github.com/devin0x01"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "China"
#  enableGitalk = true

  [params.gitalk]
    clientID = "Your client ID" 
    clientSecret = "Your client secret" 
    repo = "repo"
    owner = "devin"
    admin = "devin"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Inoreader"
    href = "https://www.inoreader.com"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/inoreader.png"
  [[params.links]]
    title = "V2EX"
    href = "https://www.v2ex.com"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/v2ex.png"
  [[params.links]]
    title = "OSChina"
    href = "https://www.oschina.net"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/oschina.png"
  [[params.links]]
    title = "InfoQ"
    href = "https://www.infoq.cn"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/infoq.png"
  [[params.links]]
    title = "博客园"
    href = "https://cnblogs.com/devin1024"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/cnblogs-app.png"
  [[params.links]]
    title = "CompilerExplorer"
    href = "https://godbolt.org"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/compiler-explorer.png"
  [[params.links]]
    title = "CppInsights"
    href = "https://cppinsights.io"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/cppinsights.png"
  [[params.links]]
    title = "QuickBench"
    href = "https://quick-bench.com"
    icon = "https://cdn.jsdelivr.net/gh/devin0x01/myimages@logo/logo/quick-bench.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]